export const players = {
  PG: {
    "Reed Sheppard": {
      firstName: "Reed",
      lastName: "Sheppard",
      team: "Houston Rockets",
      positions: "PG,SG",
      Rank: 38,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    "Collin Gillespie": {
      firstName: "Collin",
      lastName: "Gillespie",
      team: "Phoenix Suns",
      positions: "PG,SG",
      Rank: 27,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
  },
  SG: {
    "Donte DiVincenzo": {
      firstName: "Donte",
      lastName: "DiVincenzo",
      team: "Minnesota Timberwolves",
      positions: "PG,SG",
      Rank: 26,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    "Desmond Bane": {
      firstName: "Desmond",
      lastName: "Bane",
      team: "Orlando Magic",
      positions: "SG, SF",
      Rank: 36,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
  },
  PF: {
    "Toumani Camara": {
      firstName: "Toumani",
      lastName: "Camara",
      team: "Portland Trail Blazers",
      positions: "SF,PF,C",
      Rank: 87,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    "Jaden McDaniels": {
      firstName: "Jaden",
      lastName: "McDaniels",
      team: "Minnesota Timberwolves",
      positions: "SF,PF",
      Rank: 30,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    "Scottie Barnes": {
      firstName: "Scottie",
      lastName: "Barnes",
      team: "Toronto Raptors",
      positions: "SG,SF,PF,C",
      Rank: 8,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
  },
  SF: {
    "Mikal Bridges": {
      firstName: "Mikal",
      lastName: "Bridges",
      team: "New York Knicks",
      positions: "SG,SF,PF",
      Rank: 9,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    "Kon Knueppel": {
      firstName: "Kon",
      lastName: "Knueppel",
      team: "Charlotte Hornets",
      positions: "SG,SF",
      Rank: 19,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    "Keldon Johnson": {
      firstName: "Keldon",
      lastName: "Johnson",
      team: "San Antonio Spurs",
      positions: "SF,PF",
      Rank: 85,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    "Derrick White": {
      firstName: "Derrick",
      lastName: "White",
      team: "Boston Celtics",
      positions: "PG,SG",
      Rank: 12,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
  },
  C: {
    "Derik Queen": {
      firstName: "Derik",
      lastName: "Queen",
      team: "New Orleans Pelicans",
      positions: "PF,C",
      Rank: 77,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    "Karl-Anthony Towns": {
      firstName: "Karl-Anthony",
      lastName: "Towns",
      team: "New York Knicks",
      positions: "PF,C",
      Rank: 13,
      stats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
  },
}; // Данные игроков
